### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by eszn** [HackerPoet/NonEuclidean#42] opened 2021-06-07 06:09 UTC
I added glew to the main directory. Textures look like this. I have opengl and everything installed on my computer.
![image](https://user-images.githubusercontent.com/30605517/120967410-a3747300-c724-11eb-9fed-60d81189716a.png)

**Comment by BigYognes** [comment] 2021-06-07 15:40
mine just black

**Comment by the-one-with-raspberry** [comment] 2021-07-05 12:09
> mine just black

mine too

**Comment by ehx-v1** [comment] 2021-08-04 16:30
Possible duplicate of #35

**Comment by ToKiNoBug** [comment] 2021-10-04 15:47
me too

**Comment by ToKiNoBug** [comment] 2021-10-04 15:47
> > mine just black
> 
> mine too

me too

**Comment by ehx-v1** [comment] 2021-10-10 17:48
> > > mine just black
> > 
> > 
> > mine too
> 
> me too

Possible duplicates of #13

**Comment by the-one-with-raspberry** [comment] 2021-10-13 07:11
deep fried

**Closed as completed** 2023-01-29 03:46 UTC
